const invalids = [
  '.DS_Store',
  '._.DS_Store',
  '$RECYCLE.BIN',
  '(-) Game Data',
  'Common Files',
  'desktop.ini',
  'Microsoft',
  'ModifiableWindowsApps',
  'Uninstall Information',
  'Windows Defender',
  'Windows Defender Advanced Threat Protection',
  'Windows Mail',
  'Windows NT',
  'Windows Photo Viewer',
  'Windows Sidebar',
  'WindowsApps',
  'WindowsPowerShell',
  'Application Verifier',
  'Internet Explorer',
  'Microsoft Update Health Tools',
  'NVIDIA Corporation',
  'Microsoft SDKs',
  'Microsoft XNA',
  'Reference Assemblies',
  'Windows Kits',
];

export default invalids
